macrosynergy/macrosynergy

- macrosynergy/panel/make_zn_scores.py
- macrosynergy/signal/target_positions.py
- tests/unit/signal/unit_target_positions.py
Calculation of positions from line 270 downward does not need to consider start and end dates.
That is
Hence you can drastically shorten code and change structure
[1] first calculate volatility adjustment ratios (and close condition scope)
[2] the calculate positions for non-targeted and vol-targeted version in one block
=> just make sure vol-targeted positions are multiplied with vol-adjustment ratios
> Ralph mainly modifies target_positions for further work

- macrosynergy/panel/hedge_ratio.py
- tests/unit/panel/test_hedge_ratio.py
hedge_ratio seems mostly fine, but please check out the todos in the pull request
Some clean-up for efficiency and transparency is needed in hedge_calculator.
Pandas offers functions to solve some custom problems quickly.
I suggest the following for getting hedge ratios into a frame:
[1] fill pre-allocated df with estimates on days of estimation
[2] upsample to original businness day frame with asfreq() and 'ffill'
[3] then use .shift(1)
You would need neither date_weekend nor the lambda function date_adjustment.
In the test file you should add test of correct hedge ratio by comparing one or more ratio with a
regression result generated outside the functions.
> small changes and todos for hedge ratio

- macrosynergy/panel/category_relations.py
There are still two issues to solve.
[1] the separator='cids' option does not plot the correct regplots but rather the same regplot for all cross sections. You need a wide dataframe to solve this, I think. See Todo line 375
[2] the separator=<int> works but the presentation of the table is not for publication. Rather than two different tables, please create a single one, with two rows and simply assign the color of the periods to the color of font or background of the numbers, with first (oldest) period being in first row. Also, font size should be same as single table.
> reg_scatter issues

- macrosynergy/panel/category_relations.py
- macrosynergy/pnl/naive_pnl.py
Refactoring of code - task still incomplete.
> Feature/naive_pnl 

- macrosynergy/panel/make_zn_scores.py
- tests/unit/panel/test_zn_scores.py
I simplified make_zn_score and gathered all expanding means and mean absolute values into one function. The shorted the code from 550 to 180 lines (<50 lines excluding docstrings)
However, even the present code is still fairly long for careful reviews for a function whose correctness is essential for our business. Moreover, I have done very little testing. So I am sure there are bigs and errors left.
Therefore, unit testing must focus on double-calculating values and check if they are as expected.
In particular, please use pandas .expanding() function to check out calculations for specific columns and re-estimation dates.
> Ralph simplifies make_zn_scores 

- .github/workflows/integration-tests.yml
- macrosynergy/dataquery/api.py
- macrosynergy/dataquery/auth.py
- pytest.ini
- tests/integration/dataquery/__init__.py
- tests/integration/dataquery/test_dataquery.py
- tests/unit/dataquery/test_api.py
* Simplified the DataQuery requests GET and POST structure to allow for easier `mock.patch` in the unittests
*  Added an example integration test
Need to use the below example for unit and integration test to build out proper coverage for the DataQuery interfrace.
> DataQuery Unittest and Integration test examples

- macrosynergy/panel/view_ranges.py
xcat_labels added - comparable to naive_pnl.py implementation.
> xcat_labels added.

- macrosynergy/dataquery/auth.py
Changed the base URL for `OAUTH_BASE_URL` so it matches `CERT_BASE_URL`.
This avoids the issue of an extra forward-slash in the generated DataQuery Heartbeat URLs
> Changed L11 to avoid an extra '/' in the API URLs

- macrosynergy/panel/basket.py
Updated the call to sns.lineplot; same reasons as Pull Request https://github.com/macrosynergy/macrosynergy/pull/524.
TLDR - changed arguments to use a non-deprecated, backward compatible one.
> Updated call to sns.lineplot to use "estimator" instead of "ci"

- macrosynergy/panel/view_timelines.py
The "ci" (confidence interval) argument/keyword specifies a method for creating error-bars in lineplots  `seaborn` (up to and incl. version 11.2).
In `seaborn` version 12 onwards, this has been deprecated, and replaced by the `estimator` keyword, which allows the user to specify which estimator to use. 
The implication is that seaborn ignores the argument, and goes on to run error-bar estimation calculations on the data.
It is does not cause a single lineplot to be significantly slower, however when using a panel with multiple lineplots (seaborn.FacetGrid), the output takes much longer.
The issue is documented on the seaborn repository issues here : https://github.com/mwaskom/seaborn/issues/3006
To which the solution (implemented in this commit) is also provided by repo. owner : …
> changed  "ci" keyword to "estimator" in sns.lineplot calls in view_timelines.py

- macrosynergy/management/check_availability.py
The error was due to NaN types in pandas dataframes. 
The code requires the dataframe values to be converted to numerical types. However, NaN cannot be represented in integers, as numpy (a core pandas dependency) does not provide this functionality. Therefore, we cast the values to floating-point numbers (floats) which provide functionality for NaN (as well as inf.).
This is a documented [pandas "gotcha"](https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html).
Refs: 
https://pandas.pydata.org/pandas-docs/stable/user_guide/gotchas.html#support-for-integer-na
and
https://stackoverflow.com/a/21290084/4417821
> Fixed bug arising due to a type error

- tests/integration/dataquery/test_dataquery.py
Adding extra days to integration tests to make sure it works when data has not been updated for a while
> Updating integration test

- macrosynergy/pnl/naive_pnl.py
The default behaviour for the plot_pnls function was to output a single graph. In v0.0.18 this was changed to output a FacetGrid. Now been changed to output a single graph, but can output a facetgrid on request.
> Updated plot_pnls to include facets argument

- README.md
- Removed the install instruction for `pip install` from GitHub `main` branch.
- Updated the command for `pip install` from GitHub `develop` branch.
> Updated install instructions in README.md

- .github/workflows/python-test-pypi-package.yml
The actual token name is `TEST_PYPI_API_TOKEN` while the workflow was using `TWINE_TEST_TOKEN`
> Corrected GH secrets token name in TestPyPI workflow

- .github/workflows/python-test-pypi-package.yml
Correcting token names used by the Test PyPI workflow;
`TWINE_TEST_TOKEN` → `TEST_PYPI_API_TOKEN`
> develop -> test

- README.md
- docs/source/conf.py
- setup.py
Updating read me
changing sphinx to autoupdate
updating pypi to include documentation link
> Updating readme

- macrosynergy/dataquery/api.py
Changed the DataQuery API batch size from 10 to 20 requests; as per @lsimonsen
> Changed DataQuery API batch size from 10 to 20

- setup.py
Updating version number to 0.0.21.
[Issue #590 (Ralph adds just one letter)](https://github.com/macrosynergy/macrosynergy/pull/590) will not merge without version number update.
> updated version number to v0.0.21

- macrosynergy/dataquery/api.py
- macrosynergy/dataquery/auth.py
- tests/unit/dataquery/test_api.py
Add optionality to modify the BASE URL's and to use a proxy server for connecting to JPMorgan DataQuery.
> DQ API add optional proxy server function

- .github/workflows/codeql-analysis.yml
- .github/workflows/integration-tests.yml
- .github/workflows/python-package.yml
- .github/workflows/pythons-docs.yml
- Problem:
Github raised the following warning:
- Fix:
Updated actions to use the the latest versions actions/checkout(v2→v3) and actions/setup-python(v2&3→v4).
> updated GH-actions versions

- .github/workflows/pythons-docs.yml
Pinning Sphnix and sphinx RTD theme versions in documentation build workflows. This is recommended practice : https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies
Also removed sphinx book theme as it is not being used
> pinning sphinx (and sphinx themes') version

- macrosynergy/management/check_availability.py
Python Datetime's/Pandas' `isocalender()` represents a date in the form (Year, Week number, Week day). One of the calculations was using an a deprecated form of getting the year for the calculations. Updating the code to use `pd.DatetimeIndex.isocalender()` fixed the issue. Important point to remember is that the `isocalender()` functionality must NOT be confused with `isoformat()`.
> Bugfix in business_day_dif

- macrosynergy/download/dataquery.py
- Addressing and catching `requests.exceptions.ChunkedEncodingError` in `ms.download.dataquery.dq_request()`. The code will still break and raise `ms.download.exceptions.InvalidResponseError`.
- Changed function that calculates DQ API delay parameter. (https://github.com/macrosynergy/macrosynergy/issues/619). Now the delay is 200ms for requests with num. tickers<1000, and 300ms for requests with num. tickers>1000.
> Bugfixes in macrosynergy/download/dataquery.py

- macrosynergy/download/dataquery.py
- macrosynergy/download/jpmaqs.py
In case there is an unhandled exception or a failure when downloading/parsing/returning DF from JPMaQS.download, entire log stream (only from ms.download.jpmaqs.py and ...dataquery.py) will be printed to the users console.
In case there are errors with dataquery, these logs can be used as is to show the complete error.
By design, in case of an error all the logs are printed. However, if the user still needs debug logs, these can be printed by adding a `print_debug_data=True` param in the JPMaQS object init, or to JPMaQS.download.
eg:
```
with JPMaQSDownload(client_id=client_id, client_secret=client_secret, 
print_debug_data=True,) as JPMaQS:
start = timer()
df = JPMaQS.download(
tickers=tickers,
start_date="2000-01-01",
metrics=["value"],)
end = timer()
```
...
or...
```
df = …
```
> Feature : Print Debug Logs

- macrosynergy/download/dataquery.py
- macrosynergy/download/jpmaqs.py
- requirements.txt
Now shows ETAs and progress bars for 
```python
with JPMaQSDownload(...) as client:
df = client.download(... show_progress=True)
```
(default is `False`).
eg. : 
```
2023-01-18T01:34:43.620624  UTC
Number of expressions requested : 1000
Requesting data :  44%|███████████              | 22/50 [00:08<00:13,  2.11it/s]
```
↓
```
2023-01-18T01:34:43.620624  UTC
Number of expressions requested : 1000
Requesting data : 100%|█████████████████████████| 50/50 [00:17<00:00,  2.83it/s]
Downloading data :  34%|████████▏               | 17/50 [00:30<00:23,  1.43it/s]
```
↓
```
2023-01-18T01:34:43.620624  UTC
Number of expressions requested : 1000
Requesting data : 100%|█████████████████████████| 50/50 [00:17<00:00,  2.83it/s]
Downloading data : 100%|████████████████████████| 50/50 [00:50<00:00, …
```
> added show_progress functionality for download

- macrosynergy/panel/__init__.py
- macrosynergy/panel/linear_composite.py
- tests/unit/panel/test_linear_composite.py
Implemented feature req. in Issue https://github.com/macrosynergy/macrosynergy/issues/638 (Linear Composites function)
> Feature : Linear Composites

- macrosynergy/pnl/naive_pnl.py
The new behaviour implies that faceted graphs will not have a legend printed; since they would have only 1 XCAT with multiple CIDS, or vice-versa.
To understand the shared-axis-labels behaviour, view the last two example calls to `pnl.plot_pnls()` in `naive_pnl.py`:
```python
pnl.plot_pnls(  pnl_cats=["PNL_GROWTH_NEG"], 
pnl_cids=cids,
facet=True,
xcat_labels=None
)
pnl.plot_pnls(  pnl_cats=["PNL_GROWTH_NEG"], 
same_y=True,
pnl_cids=cids,
facet=True,
xcat_labels=None,
share_axis_labels=False,
x_axis_label='Date',
y_axis_label='PnL',
y_label_adj=0.1,)
```
> fixed legend for non-faceted graphs; added shared-axis-label feature

- setup.py
Updated setup.py. 
Closes https://github.com/macrosynergy/macrosynergy/issues/508
> Feature : Updated setup.py for [3.7, 3.11]

- .gitignore
- macrosynergy/download/jpmaqs.py
DQ formatting specifies using YYYYMMDD as a date format, while the ISO (8601) format is YYYY-MM-DD. The package now explicitly removes the dashes while type checking to ensure the date is formatted as per DQ documentation.
> Bugfix : Changed internal date formatting

- macrosynergy/panel/view_timelines.py
- tests/unit/panel/test_view_timelines.py
Closes #685.
Added a simple code block to check if the input DF has the necessary columns of a standard DF.
If not, `df.reset_index` is attempted; if that works, good - continue. Else raises exception.
> Feature : View timelines, reset index to standardize input DF

- macrosynergy/download/dataquery.py
- macrosynergy/download/jpmaqs.py
- macrosynergy/management/utils.py
- tests/unit/management/test_utils.py
A special bug arising when the user uses a yaml like:
```yaml
oauth:
client_id: "userName"
client_secret: "passwordX"
cert_auth:
username: "username"
password: "password"
cert: "certif.crt"
key: "keyx.key"
```
It caused the recursive dict search to return the dict itself when searching for 'cert'.
Possible solutions were, 
1. force the user to use 'crt' as the dict key to the path (str).
2. add a match_type =<type> feature in the search function.
Solution 2 was implemented.
> Bugfix : Fixed Dict Search for Config 

- macrosynergy/panel/make_zn_scores.py
- tests/unit/panel/test_zn_scores.py
If a CID_XCAT pair in the dataframe is filled with NAs only, it will now be dropped and a warning will be raised.
Closes #731.
Unit tests for warning included.
> Bugfix : Make ZN Scores failing with pure NA series

- macrosynergy/download/jpmaqs.py
Currently, the interface breaks and raises an unintelligable error when a date such as 1600-01-01 is passed.
New behaviour:
A hard limit of 1677-09-22 == `pd.Timestamp.min` has to be imposed, as it would simply be impossible to create a pd.Timestamp for a date before this.
A warning message is raised if the start_date or the end_date is before 1950-01-01.
When the start_date is after the end_date, the two dates are swapped and a warning message is raised.
> Bugfix : DQ/Unexpected Dates

- macrosynergy/panel/__init__.py
- macrosynergy/panel/view_metrics.py
- tests/unit/panel/test_view_metrics.py
Closes #660 .
Slightly modified implementation of function described in #660, view_lags.
Implementation here is for generic non-value metric. 
Docstring:
```python
"""
A function to visualise the `eop_lag`, `mop_lag` or `grading` metrics for a given
JPMaQS dataset. It generates a heatmap, where the x-axis is the observation
date, the y-axis is the ticker, and the colour is the lag value.
:param <pd.Dataframe> df: standardized DataFrame with the necessary columns:
'cid', 'xcat', 'real_date' and 'grading', 'eop_lag' or 'mop_lag'.
:param str xcat: extended category whose lags are to be visualized.
:param <List[str]> cids: cross sections to visualize. Default is all in DataFrame.
:param <str> start: earliest date in ISO format. Default is earliest available.
:param <str> end: latest date in …
```
> Feature : View Metrics ~view lags~

- tests/unit/test_package.py
Fails on a Windows system where the user may have a space such as `C:/User Name/script.py`
> Bugfix: `test_package.py`, Failing on Windows systems

- macrosynergy/download/dataquery.py
- macrosynergy/download/exceptions.py
- tests/unit/download/test_dataquery.py
DataQuery confirmed that client_id or the username for a certificate need not be treated as secret, and can be printed to the console for debug/error info. These changes allow that.
> Feature : Error info to include `client_id`/cert `username` as a generic `user_id`

- macrosynergy/panel/view_timelines.py
Added a feature to adjust the font-size and the x-position of the title of a view_timelines plot.
Docstring:
```python
"""
:param <float> title_xadj: parameter that sets x position of title. Default is 0.5.
:param <int> title_fontsize: font size of title. Default is 16.
"""
```
This also hints that either:
[1] All visual functions must include an <attr>x_adj and <attr>y_adj;
[2] Or they must support the use of an X-Y tuple as the <attr>_adj variable
> Feature: `view_timelines` - Title-fontsize and Title-X-Pos adjustment

- macrosynergy/panel/view_ranges.py
Seaborn deprecated the use of the `ci` parameter in favour of allowing a more generic `...errorbar=('<type>', threshold)` in [Seaborn v0.12.2](https://github.com/mwaskom/seaborn/releases/tag/v0.12.2) ([Seaborn/#2407](https://github.com/mwaskom/seaborn/pull/2407/)).
This has not yet effected the regplot, but will at some point in the future (see[ Seaborn/WhatsNew/0.12.0](https://seaborn.pydata.org/whatsnew/v0.12.0.html#more-flexible-errorbars)).
Thanks @mikiinterfiore for spotting this and the creating the PR.
> Bugfix : `view_ranges`/`sns.barplot`, `ci` param deprecated

- macrosynergy/panel/category_relations.py
- tests/unit/panel/test_category_relations.py
The function has a print statement. This implies the function can have behavior that can't be easily tested, or passed on to functions that may use it. (related - #803)
> Bugfix: Added warning behavior to `CategoryRelations.intersection_cids`

- macrosynergy/download/dataquery.py
- macrosynergy/download/exceptions.py
- tests/unit/download/test_dataquery.py
DQ will be changing the group-id associated with the JPMaQS dataset. This is a change to retry with the new group-id if the old one fails. Later, when the change is confirmed, the "new" group-id will be tried before the old one. Of course, ultimately, the old one will be removed
> Feature : Added alternate `group-id` for DQ Catalogue

- macrosynergy/signal/signal_return.py
- tests/unit/signal/test_signal_return.py
Adding a method `apply_slip()` to `SignalReturnRelations`.
The function is a replica of [`CategoryRelation.apply_slip()`](https://github.com/macrosynergy/macrosynergy/blob/d129d0ed1a0750c2a12d87c1b9a68f03f70ffc5e/macrosynergy/panel/category_relations.py#L157).
Closes https://github.com/macrosynergy/macrosynergy/issues/802
Once the functionality is verified independently for both these functions, they'll be merged to a common utility/DF tool.
> Feature: Adding slippage functionality to SignalReturnRelations

- macrosynergy/download/dataquery.py
Now prints :
```python
User ID: OAuth_ClientID : <clientID>
```
or
```python
User ID: CertAuth_Username : <cert_username> 
```
> Feature : DataQuery.py - Added a tag of OAuth/CertAuth with User-ID

- macrosynergy/download/dataquery.py
- macrosynergy/download/exceptions.py
`dataquery.OAuth` was trying to fetch the OAuth token with `self.proxy`. This was being confused with `dataquery.DataQueryInterface.proxy`. 
Another small change has been made to the printing and generating method of the User ID
> Bugfix : Proxy not being handled correctly for API/Oauth Flow

- macrosynergy/download/dataquery.py
In case the user provides `oauth=True`, but no oauth credentials, the error gneerated is not very helpful. This PR fixes that.
> Bugfix : Cert fallback for OAuth

- macrosynergy/panel/linear_composite.py
- macrosynergy/panel/view_timelines.py
- tests/unit/panel/test_linear_composite.py
The argument was not needed and was partially in conflict with the specified docstring in #823
> Bugfix : Removing `vweights_threshold` param from linear_composites

- macrosynergy/panel/view_ranges.py
> Feature : Hide legend in `view_ranges()` when a single xcat is being shown

- .github/workflows/python-package-release.yml
- .github/workflows/python-package.yml
Unittests for PRs to Develop and Test will now run on os=ubuntu-latest and python=3.11 only.
PRs to Main will run on os=[Windows, MacOS, Ubuntu] and python=[3.8, 3.9, 3.10, 3.11]
> Feature : Changing Unit Testing strategy for CI/CD branches

- .github/workflows/python-package-release.yml
- setup.py
Earlier PR had GH workflow tests running on Windows & MacOS. These tests are not identical to Ubuntu, and need to be run differently
> Test←Develop for v0.0.32

- macrosynergy/download/dataquery.py
The group id for the JPMaQS dataset will change from `CA_QI_MACRO_SYNERGY` to `JPMAQS` on June 10.
There was a soft fix for this in v0.0.30, which would try the old ID first, followed by the new ID. This PR changes that to try the new ID first, and then the old ID.
> Feature : Update DQ Group ID

- tests/unit/panel/test_view_metrics.py
The unittest sets backend to "Agg"; this PR makes changes to the effect of:
```python
mpl_backend: str = matplotlib.get_backend()
matplotlib.use("Agg")
matplotlib.use(mpl_backend)
```
> Bugfix : `view_metrics()` unittest backend reset

- macrosynergy/panel/view_timelines.py
- tests/unit/panel/test_view_metrics.py
- tests/unit/panel/test_view_timelines.py
[macrosynergy.panel.view_timelines()](https://github.com/macrosynergy/macrosynergy/blob/develop/macrosynergy/panel/view_timelines.py) has had issues to do with alignment and passing the correct directives to the backends - matplotlib and seaborn.
Since matplotlib operates on mostly global runtime settings, seaborn is able to overwrite and use these; however for our purposes the crossover causes a lot of headaches where directives to the backends interfere and cause undesirable behaviour.
The new refactor uses only matplotlib with the special addition of `plt.tight_layout()` - which uses a form of constraint solver to achieve a desired state. This now allows us to use `view_timelines()` with very minimal adjustment/additional arguments, except for data args and most likely size.
Even …
> Feature : Refactor `view_timelines`

- macrosynergy/panel/linear_composite.py
As intended, the default values for weights would be
```python
weights: List[float] = [ 1/len(xcats) ] * len(xcats)
signs: List[int] = [ 1 ] * len(xcats)
```
There was a bug where the type checking of the two variables was being done before checking/handling if they were=`None`.
Closes #863
> Bugfix : `linear_composite` default values for `weights` and `signs`

- macrosynergy/panel/make_relative_value.py
- tests/unit/panel/test_relative_value.py
The function has a print statement. This implies the function can have behavior that can't be easily tested, or passed on to functions that may use it.
> Bugfix: Warning added to `_prepare_basket` 

- macrosynergy/management/check_availability.py
- tests/unit/management/test_check_availability.py
**Modifies default behaviour**
Currently, the last date used to check availability is the last date for which data is available in the passed dataframe.
This PR changes this functionality to use the last-business-day before today as the default "last day"
Closes #865
> Feature : Check availability to use last business day as benchmark

- macrosynergy/panel/linear_composite.py
- tests/unit/panel/test_linear_composite.py
**Modifies default behaviour**
Currently the underlying functions `linear_composite_on_xcat()` & `linear_composite_on_cid()` have arguments for  `normalize_weights`. However, the call to these functions had the flag hardcoded. This arg has now been added to the wrapper, with a pass-through.
Another bugfix - some arguments are modified before being passed to the backend. There is a `.copy()` to prevent modifying them outside the current scope.
> Bugfix: `linear_composite()`, added pass-through for `normalize_weights` arg

- tests/unit/panel/test_relative_value.py
This makes a very small change -
Instead of checking :
`np.all(arrayX == arrayY)`
it checks 
`np.allclose(arrayX, arrayY)`
The key difference is that the latter introduce an absolute and relative tolerance.
For most cases this should work exactly the same, except when looking at very minute changes (default `r_tol = 1e-05`, `a_tol = 1e-08`)
> Bugfix: Fixing `test_relative_value`

- macrosynergy/management/check_availability.py
> Bugfix: `check_availability()` - negative missing days

- macrosynergy/panel/panel_timeseries_split.py
In think I understood most of the code, but am not 100% sure.
This has a number of the TODOs, but only a few major ones.
* The repetive code parts should be combined.
* Split dates and sample start dates should be clearer disentangled.
The minimum logic of interval learning must work as follows:
The first valid training sample must satisfy both min_cids and min_periods conditions.
However, the start date can be before the first date for which min_cids is satisfied,
We do not want to waste the experiences of countries with long history.
The max_periods condition may apply.
Please add a little commentary to explain the intentions of code sections
Also always inform about what methods return with return keyword.
> adds code intention comments and TODOs

- macrosynergy/management/check_availability.py
Bug #913 causing some problems
> Bugfix: `check_availability()`, negative last updated date

- .github/workflows/python-package-release.yml
- .github/workflows/python-package.yml
- .github/workflows/python-publish-docs.yml
- .github/workflows/python-test-pypi-package.yml
- .github/workflows/pythons-docs.yml
- pyproject.toml
- pytest.ini
- setup.cfg
- setup.py
The functionality for `setup.py`, `setup.cfg`, and `pytest.ini` is fully supported via a `pyproject.toml`.
This is valid for Python 3.8+, which is already the cut-off for current supported Python versions
> Refactor: Removing Python legacy configuration files

- .coveragerc
- pyproject.toml
`[tools.coverage]` allows coverage RC directives to be put into `pyproject.toml`
> Refactor: Moved `.coveragerc` into `pyproject.toml`

- docs/scripts/build_md.py
- macrosynergy/download/dataquery.py
- macrosynergy/download/jpmaqs.py
- macrosynergy/management/check_availability.py
- macrosynergy/management/simulate_quantamental_data.py
- macrosynergy/management/update_df.py
- macrosynergy/panel/basket.py
- macrosynergy/panel/converge_row.py
- macrosynergy/panel/historic_vol.py
- macrosynergy/panel/linear_composite.py
- macrosynergy/panel/make_blacklist.py
- macrosynergy/panel/make_relative_value.py
- macrosynergy/panel/make_zn_scores.py
- macrosynergy/panel/panel_calculator.py
- macrosynergy/panel/return_beta.py
Currently functional directives-
```
::docs::function_name::sort_first::
::docs::function_name::sort_last::
```
As of now, all directives within a module are parsed together. i.e. it wouldn't matter if you were addressing some other function in a functions docstring.
For this reason, it is recommended to list these directives in the module docstring.
Future directives can include highlighting, more sorting, and even appending examples
> Feature: Added ability to pass directives in docstrings

- macrosynergy/management/utils.py
The functions `return` was at the wrong indentation level
> Bugfix: `msm.utils.standardise_dataframe`, code indentation

- macrosynergy/panel/category_relations.py
> Bugfix: `CategoryRelations`, missing XCAT error message

- docs/requirements.txt
- pyproject.toml
> Feature: Updating `pyproject.toml`

- macrosynergy/download/jpmaqs.py
The file had `sys.path.append...` and unsorted imports
> Bugfix: Cleaning up imports in `jpmaqs.py`

- macrosynergy/management/simulate_quantamental_data.py
- macrosynergy/panel/linear_composite.py
- macrosynergy/visuals/view.py
- tests/unit/management/test_simulate_quantamental_data.py
- tests/unit/panel/test_linear_composite.py
- tests/unit/panel/test_panel_calculator.py
The function used `start_date` and `end_date` to specify dates, whereas the rest of the package uses `start` and `end` (with the notable exception of `ms.download`)
> Bugfix: Standard keywords in `make_test_df()`

- macrosynergy/visuals/view.py
There was an error where the `cumsum` operation would take the earliest start date in the dataframe instead of the specified start date. this PR fixes that
> Bugfix: Cumulative Sum, `msv.view.timelines`

- macrosynergy/management/utils.py
- tests/unit/management/test_utils.py
The function depended on an underlying function (dt.datetime.strptime) to raise a type error when a non-string value was passed. The unittests for the same function has been enhanced.
> Bugfix: `is_valid_iso_date`

- macrosynergy/download/jpmaqs.py
- tests/unit/download/test_dataquery.py
> Bugfix: `JPMaQSDownloader`, downloading generic DQ expressions

- macrosynergy/panel/view_correlations.py
- tests/unit/panel/test_view_correlations.py
This PR allows the `xcats` or `cids` parameters of the `correl_matrix` function to take a list containing two lists. In this case, the correlation will be calculated and visualized between these two sets. 
If both sets contain a single category, such as `xcats = [['XR'], ['CRY']]`, correlation will be visualized between the cross-sections of these categories. If either set contains more than one category, correlation is visualized between categories.
> Feature: extend `correl_matrix` to calculate correlation between two sets

- macrosynergy/learning/__init__.py
- macrosynergy/learning/panel_timeseries_split.py
- tests/unit/learning/test_paneltimeseriessplit.py
DO NOT MERGE UNTIL RALPH HAS REVIEWED.
> Feature: new `panel_cv_scores` to return cv scores over a panel 

- macrosynergy/management/utils.py
- macrosynergy/visuals/__init__.py
- macrosynergy/visuals/heatmap.py
- macrosynergy/visuals/plotter.py
- macrosynergy/visuals/view.py
- macrosynergy/visuals/view/__init__.py
- macrosynergy/visuals/view/metrics.py
- macrosynergy/visuals/view/timelines.py
- tests/unit/management/test_utils.py
- tests/unit/panel/test_view_metrics.py
- tests/unit/visual/test_heatmap.py
- tests/unit/visual/test_view_metrics.py
- Added the `Heatmap` class in `visuals/`.
- The implementation of the `view_metrics` function was moved into `view/metrics.py` and now uses the Heatmap class for plotting.
> Feature: view metrics refactor

- .github/workflows/github-update-cache.yml
Workflows can share caches built on the default branch. This PR adds logic that creates/checks the cache on every push to develop - accessible by all PRs made against develop.
Source: 
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cach
and 
https://stackoverflow.com/a/71061281
> Feature: Common cache on the `develop` branch

- .github/scripts/check_pr.py
- .github/workflows/github-pr-tests.yml
- docs/static/05_dev_guide.md
Pull request titles are essential to conveying version history for features as well as documenting changes. They are also used for generating release notes and developer logs (see https://github.com/macrosynergy/macrosynergy/pull/1070).
This PR introduces tests that assert a logical naming convention to PR titles.
This PR also introduces PR directives, which effectively allow the author to block/automatically approve merges depending on another PRs status.
See [Docs/Contribution_Guide/Pull_Requests/Merge_Queueing](https://github.com/macrosynergy/macrosynergy/blob/feature/enforce_branch_names/docs/static/05_dev_guide.md#merge-queueing) for more info
> Feature: CI/CD, Pull request QC and directives

- macrosynergy/panel/view_correlations.py
If two sets of categories are supplied through `xcats` and `xcats_secondary`, `lags` and `lags_secondary` should specify lags for these sets respectively. Previously, `lags` would specify lags for both sets if `lags_secondary` was empty.
> Bugfix: fix lags for `correl_matrix`

- macrosynergy/learning/panel_timeseries_split.py
- macrosynergy/signal/signal_return.py
- macrosynergy/visuals/plotter.py
With the release of [Matplotlib version 3.8.0](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.8.0.html), the use of `seaborn-<foo>` styles has been deprecated. Their recommendation is use `seaborn-v0_8-<foo>` instead, or directly use the seaborn API.
See [Matplotlib/Changes for 3.8.0/Removal of Deprecated APIs](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#removal-of-deprecated-apis) fortheir release notes
> Bugfix: Seaborn/Matplotlib style issue

- macrosynergy/management/__init__.py
- macrosynergy/management/types.py
- macrosynergy/visuals/__init__.py
- macrosynergy/visuals/common.py
- macrosynergy/visuals/facetplot.py
- macrosynergy/visuals/heatmap.py
- macrosynergy/visuals/lineplot.py
- macrosynergy/visuals/view.py
- tests/unit/management/test_types.py
- tests/unit/management/test_utils.py
(Merge in version v0.0.45)
This PR moves some common types from their current subpackages to `macrosynergy.management.types` to allow for extensive and consistent usage across subpackages.
For reference, intention can be summarized by changes made in PR : https://github.com/macrosynergy/macrosynergy/pull/1071
> Feature: Custom types and `isinstance()` checks

- macrosynergy/management/types.py
- macrosynergy/management/utils.py
- tests/unit/management/test_utils.py
`qdf_to_ticker_df()` was missing `df = df.copy()`
> Bugfix: Side-effects in `qdf_to_ticker_df()` util.

- macrosynergy/signal/signal_base.py
> Feature: Add warning to when cids specified in Signal Base are not in the reduced dataframe

- macrosynergy/panel/view_ranges.py
- macrosynergy/visuals/ranges.py
This pull request adds the ability to specify the location and bbox of the legend in the `view_ranges` function. This is achieved by passing the `legend_loc` and `legend_bbox_to_anchor` arguments to `ax.legend`.
Commits included:
- adding legend loc args and docstrings
- added loc and bbox_to_anchor pass-through to ax.legend
- Add legend location and bbox to `view_ranges`, for pass-through to `msv.view_ranges`
No issues fixed.
> Bugfix: Add legend location and bbox args to `view_ranges()`

- macrosynergy/management/constants.py
- macrosynergy/management/utils/__init__.py
- macrosynergy/management/utils/df_utils.py
- macrosynergy/panel/category_relations.py
- macrosynergy/panel/historic_vol.py
- macrosynergy/panel/make_zn_scores.py
- macrosynergy/panel/return_beta.py
- macrosynergy/visuals/correlation.py
- tests/unit/panel/test_return_beta.py
- tests/unit/panel/test_view_correlations.py
- We should always be using business date frequencies `B`, `W-FRI`, `BM`, `BQ`, `BA`, instead of `D`, `W`, `M`, `Q`, `A`.
- Methods will continue to expect `D`, `W`, `M`, `Q`, or `A` as arguments but they'll be mapped to their business date counterpart.
> Feature: use business day freq

- macrosynergy/download/dataquery.py
This pull request removes the usage of the old group-id "CA_QI_MACRO_SYNERGY" from the DQ.get_catalogue method. The method now only uses the provided group-id parameter to fetch the response from the server. This change ensures that the code is up to date and removes unnecessary code.
Closes #1036
> Feature: Remove old group-id from `DataQueryInterface.get_catalogue()`

- macrosynergy/learning/__init__.py
This pull request refactors the imports in the learning module to improve code readability and maintainability. The changes include:
- Importing the `BasePanelSplit` class from the `panel_time_series_split` module.
- Importing the `LassoSelectorTransformer`, `MapSelectorTransformer`, and `BenchmarkTransformer` classes from the `transformers` module.
- Importing the `panel_significance_probability`, `sharpe_ratio`, `sortino_ratio`, `regression_accuracy`, and `regression_balanced_accuracy` functions from the `metrics` module.
- Importing the `AdaptiveSignalHandler` class from the `prediction_tools` module.
These changes ensure that the necessary classes, functions, and metrics are imported correctly and organized in a more structured manner.
> Refactor: Refactored imports in learning module

- .github/workflows/python-publish-docs.yml
- .github/workflows/python-pypi-upload.yml
- .github/workflows/python-test-docs.yml
- .github/workflows/python-test-pypi-upload.yml
- .github/workflows/python-unit-tests-release.yml
- .github/workflows/python-unit-tests.yml
This pull request refactors the flake8 linting commands in the codebase. The changes include excluding the `docs`, `scripts`, and `build` folders from the linting process. Additionally, certain errors are now treated as warnings. These changes improve the efficiency and accuracy of the linting process.
> Refactor: Updating `flake8` directives

- macrosynergy/visuals/__init__.py
- pyproject.toml
Older versions of Seaborn not fully compatible with older versions of matplotlib. Simply pushing seaborn to the latest dependency fixes the issue.
Closes #1267
> Bugfix: Seaborn version/Missing heatmap annotations

- macrosynergy/signal/signal_return_relations.py
> Bugfix: Ensure negation of signals is reverted

- macrosynergy/signal/signal_return_relations.py
- tests/unit/signal/test_signal_return_relations.py
return signal and frequency in correlation bars
> Feature: Add functionality to specify feature and return signal in correlation bars

- tests/unit/learning/test_transformers.py
Using `setUpClass` instead of `setUp` in unit tests so that the setup is done once per class rather than before each test. This is especially important for `TestMapSelector` since using `MixedLM` is expensive.
> Feature: speed up learning tests

- docs.old/assets/jpb-config.yml
The docs-site hosted on docs.macrosynergy.com has an outdated URL for the logo.
this PR fixes that. Given that the docs can be deployed by workflow dispatch, a new version is not required for this change - as it can be directly deployed from this branch.
> Bugfix: Update logo URL in JPB docs site

- .github/workflows/python-publish-docs.yml
- .github/workflows/python-pypi-upload.yml
This PR changes the trigger event for publishing the docs on GitHub pages.
Currently, the docs are updated on push to main. 
Given that the release notes on the docs-site require a release to be published on GitHub to generate notes for the latest version, the docs will now be pushed as part of the upload to PyPI (which itself is triggered when a release is published).
The old workflow for publishing docs still remains, but only with a workflow dispatch trigger.
> Feature: Update publish trigger for docs-site

- macrosynergy/download/dataquery.py
- tests/unit/download/test_dataquery.py
Lowering the delay parameter below 200ms only throws an Runtime Warnings now, whereas it would throw a ValueError earlier.
In cases where a request fails and the `request_wrapper()` does a retry, the default `API_DELAY_PARAM (300ms)` will be used (the user cannot edit this.
Use as:
```python
with JPMaQSDownload(..., dq_download_kwargs={"delay_param" : 0.1}) ...
```
> Feature: Updating delay param code

- macrosynergy/management/utils/check_availability.py
- macrosynergy/management/utils/df_utils.py
- macrosynergy/panel/basket.py
- macrosynergy/panel/historic_vol.py
- macrosynergy/panel/return_beta.py
- macrosynergy/panel/view_correlations.py
- macrosynergy/panel/view_ranges.py
- macrosynergy/panel/view_timelines.py
- macrosynergy/signal/target_positions.py
- macrosynergy/visuals/correlation.py
- macrosynergy/visuals/ranges.py
- macrosynergy/visuals/timelines.py
This pull request fixes the column names in the DataFrame specification. The QDF spec. has columns 'xcat' as a column, whereas 'xcats' had been used in the docstrings
> Bugfix: Fix QDF column names in docstrings

- macrosynergy/management/simulate/simulate_vintage_data.py
- tests/unit/management/test_vintage_data.py
This pull request adds unit tests for the VintageData class in the simulate module. The tests cover the make_grade1, make_grade2, and make_graded methods, ensuring that the generated dataframes have the expected structure and values.
> Feature: Add unit tests for VintageData class

- macrosynergy/download/dataquery.py
- macrosynergy/download/jpmaqs.py
`...check_connection()` was being called too frequently in the download process. Removed on of those calls, and added a `time.sleep(0.2)` in the check_connection call.
> Bugfix: Fix `JPMaQS.check_connection()` calls and delay param

- docs/format_docstrings.py
- docs/gen.py
- macrosynergy/learning/metrics.py
- macrosynergy/learning/panel_time_series_split.py
- macrosynergy/learning/signal_optimizer.py
- macrosynergy/learning/transformers.py
- macrosynergy/management/simulate/simulate_quantamental_data.py
- tests/simulate.py
The docs generation process uses `sphinx-autodoc-typehints`.
However, our docstring format isn't directly compatible with it.
This pull request adds a script that formats the docstrings in the temporary build directory for the docs before calling the build.
Examples: 
macrosynergy.learning.transformers : 
[Before](https://macrosynergy.readthedocs.io/latest/macrosynergy.learning.transformers.html), [After](https://macrosynergy.readthedocs.io/feature-docs_params_fmt/macrosynergy.learning.transformers.html)
macrosynergy.panel.view_timelines : 
[Before](https://macrosynergy.readthedocs.io/latest/macrosynergy.panel.view_timelines.html), [After](https://macrosynergy.readthedocs.io/feature-docs_params_fmt/macrosynergy.panel.view_timelines.html) …
> Feature: Parameter formatting in docstrings

- macrosynergy/pnl/historic_portfolio_volatility.py
Simplify calculation and out basic principles for portfolio volatility based on historical variance-covariance of returns and the contract signal weights
> Setting out principles for portfolio volatility estimates

- macrosynergy/visuals/timelines.py
This pull request fixes a variable name in the timelines function. The variable name "xcats" was mistakenly used instead of "xcat". This fix ensures that the correct variable name is used, preventing any potential errors or confusion in the code.
> Bugfix: Fix variable name in `msv.timelines()` function

- macrosynergy/management/utils/df_utils.py
- tests/unit/management/test_utils.py
Reverts macrosynergy/macrosynergy#1523
> Bugfix: Revert "Bugfix: `get_eops` - fix `dates=None` behaviour"

- macrosynergy/download/dataquery.py
Added constant:
```python
TOKEN_EXPIRY_BUFFER: float = 0.9  # 90% of token expiry time.
```
which is used in the following manner:
```python
expired_token: bool = (created_at + expires_in * TOKEN_EXPIRY_BUFFER) > datetime.now()
```
> Feature: Add `TOKEN_EXPIRY_BUFFER` to `dataquery.Oauth`

- macrosynergy/management/decorators.py
- macrosynergy/management/types.py
- macrosynergy/panel/make_zn_scores.py
- macrosynergy/visuals/README.md
- macrosynergy/visuals/facetplot.py
- macrosynergy/visuals/heatmap.py
- macrosynergy/visuals/lineplot.py
- macrosynergy/visuals/timelines.py
- tests/unit/management/test_types.py
All type-hints and docstrings using `msm.types.Numeric` will now use `numbers.Number`
> Feature: Removing `msm.types.Numeric`

- macrosynergy/panel/make_zn_scores.py
`make_zn_scores` calculates mean absolute deviation not standard deviation.
> Bugfix: Update `make_zn_scores` docs

- macrosynergy/management/utils/__init__.py
- macrosynergy/management/utils/df_utils.py
- tests/unit/management/test_utils.py
Adding a function to `get_sops` (starts-of-periods) - very similar to existing [`get_eops`](https://github.com/macrosynergy/macrosynergy/blob/6c5f42885102ebc75f5e713ccda399356bfe58e8/macrosynergy/management/utils/df_utils.py#L808-L824)
> Feature: `get_sops()` - get starts-of-periods

- macrosynergy/visuals/facetplot.py
Current implemenetation raises an error due to missing plot titles when neither of `cid_grid`, `xcat_grid`, `cid_xcat_grid` = True.
> Bugfix: Fixing bug in `FacetPlot.lineplot()`

- macrosynergy/panel/panel_calculator.py
Please look over and check logic, not entirely sure if this is fully correct.
Idea of the bugfix is that when someone specifies: 
```
cidx = ['DEM', 'ESP', 'FRF', 'ITL']
calcs = [f"RIR_NSA = iEUR_RIR_NSA"]
dfa = msp.panel_calculator(dfx, calcs=calcs, cids=cidx)
```
and only EUR_RIR_NSA is in the dataframe then as of right now the intention should be to create 4 new expressions called DEM_RIR_NSA, ESP_RIR_NSA, etc... with the same values as EUR_RIR_NSA. However upon reduce_df it would get an empty df and hence throw an error. I've changed the logic of how cids are calculated so when reduce_df is called it includes the specific cids specified in the calculation as well as the cids specified in the arguments of panel calculator.
However after reducing the dataframe it then specifies the cids …
> Bugfix: Fix occurence in panel calculator of when single cid is specified

- macrosynergy/download/jpmaqs.py
- macrosynergy/management/__init__.py
- macrosynergy/management/constants.py
- macrosynergy/management/utils/df_utils.py
As per @rsueppel 's request, this PR changes the preffered way of sorting a QDF from REAL_DATE, CID, XCAT to CID, XCAT, REAL_DATE.
This does not change the actual column order for the index columns, which still remains REAL_DATE, CID, XCAT, [M],...
The column order for standard JPMaQS metrics [value,grading,eop_lag,mop_lag] is now enforced, with non-standard metrics being sorted after all standard metrics present in the df.
New output of standardise_dataframe looks like:
> Feature: Change preferred sorting order for standard QDF

- macrosynergy/visuals/lineplot.py
These arguments allow addition of horizontal/vertical dashed black lines at specific X (for vline) or Y (for hline) coordinates.
Example usage:
```python
from macrosynergy.management.simulate import make_test_df
from macrosynergy.visuals import LinePlot
cids = ["USD", "EUR", "GBP", "JPY"]
xcats = ["RIR_NSA", "FXXR_NSA", "EQXR_NSA"]
df = make_test_df(cids=cids, xcats=xcats)
LinePlot(df).plot(
title="Test Title ",
ax_hline=[45, 55],
ax_vline=["2015-4-01", "2015-09-01"],
)
```
produces:
> Feature: Adding `ax_hline` & `ax_vline` to `msv.LinePlot`

- .github/scripts/run_notebooks.py
- .github/workflows/run-notebooks.yml
- macrosynergy/panel/category_relations.py
Allows all cross sections in the dataframe to be plotted on one plot in reg_scatter: 
Bug fix is to prevent an error from being thrown when single_chart = True is called
Format change allows size adjustment of Facetplot reg scatter
> Feature: Add single_scatter argument in reg_scatter, also implement bug fixes and format issues in reg_scatter

- macrosynergy/panel/historic_vol.py
`df.ffill()` will throw a warning (and error in future) when `dtype=object` for any of the columns
> Refactor: Syntax update for `df.ffill()` 

- macrosynergy/management/utils/sparse.py
- tests/unit/management/test_sparse.py
Add three methods to the class:
* `to_dict`: creates a dictionary of the sparse data for a specific ticker.
* `to_json`: creates a JSON string from the output of `to_dict`.
* `get_releases`: extract the data release between two dates (defaults is all release from last business day till today).
> Feature: Adding `get_releases` and `to_json` methods for `InformationStateChanges` class

- macrosynergy/visuals/correlation.py
Bug: Plots generated from this function would crop the x-tick labels when showing/saving the plot.
This pull request adds the `title_fontsize` and `fontsize` arguments to the `view_correlation` function. The `plt.tight_layout` function is called to improve the spacing between the heatmap and the axis labels.
> Bugfix: Add tight layout to `view_correlation()`

- macrosynergy/management/utils/df_utils.py
- tests/unit/management/test_update_df.py
Currently `update_df` accepts and processes empty dataframes, which results in a warning from `pandas`: 
```bash
FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
```
simple fix:
```
if df_left.empty: return df_right
if df_right.empty: return df_left
```
> Bugfix: Change `update_df` to skip empty dataframes

- macrosynergy/signal/signal_return_relations.py
> Docs: Updating docstring for `SignalReturnRelations`

- macrosynergy/management/utils/df_utils.py
The `drop_nan_series` function has been refactored to use the specified column instead of hardcoding "value". This change ensures that the function is more flexible and can be used with any column in the DataFrame.
> Bugfix: Refactor `drop_nan_series` function to use the specified column

- macrosynergy/management/utils/sparse.py
- tests/unit/management/test_sparse.py
Currently, the `InformationStateChanges.__repr__` loads the entire dict with DataFrames in the repr, this can take ~1 second for larger objects
> Bugfix: improve `repr` of InformationStateChanges class

- macrosynergy/download/jpmaqs.py
These changes allow JPMaQS Download to directly use the `DQ_CLIENT_ID` and `DQ_CLIENT_SECRET` env. variables to get the client ID & secret.
e.g.:
```python
with JPMaQSDownload() as jpmaqs:
df = jpmaqs.download(...)
```
> Feature: JPMaQSDownload can now use default environment variables for authentication

- macrosynergy/management/types/qdf/methods.py
Currently, the `_sync_df_categories` raises a SettingWithCopyWarning as the dataframes being passed were 'views' of the original dataframes
> Bugfix: `_sync_df_categories`, SettingWithCopyWarning

- macrosynergy/panel/panel_calculator.py
- tests/unit/panel/test_panel_calculator.py
Improve function logic for handling cids with any length, i.e. identifying the cid as the section of the string upto the first underscore.
i.e. `CIDWITHANYLENGTH_LIKE_THIS`, will be split as `cid=CIDWITHANYLENGTH` and `xcat=LIKE_THIS`.
This PR also contains some minor documentation/formatting updates
> Bugfix: Panel calculator, using `cids` with arbitrary lengths

- macrosynergy/panel/category_relations.py
- tests/unit/panel/test_category_relations.py
Address a minor bug in the `reg_scatter` function and introduce a test for the case where labels are set to None and the separator is 'cids'.
> Bugfix: `CategoryRelations.reg_scatter()` for case with `labels=None, separator="cids"`

- macrosynergy/download/jpmaqs.py
- setup.py
Update the default behavior for end_date to use the last business day instead of a date two days ahead.
This change is being made to prevent issues with zn-scoring in notebooks, as it can happen that we download a few select series for today and then form the scored average over these few series or even a single series This would distort factors and signals and the end of the timeline.
> Feature: `JPMaQSDownload`, default `end_date` to use last business day instead of 2-days-ahead

- macrosynergy/management/utils/sparse.py
- tests/unit/management/test_sparse.py
Introduce a `score_by` parameter to the scoring methods, allowing selection between scoring based on the difference or the level of information state changes. This enhances flexibility in score calculation.
---
Closes #2219
> Feature: `InformationStateChanges`, add `score_by` parameter for z-scoring methods

- macrosynergy/panel/linear_composite.py
Correct a typo in the docstring for the `linear_composite` function to improve clarity.
> Docs: Fix typo in `linear_composite()` docstring

- macrosynergy/panel/make_zn_scores.py
At the moment, `make_zn_scores`, and `expanding_stat` will fail if called with dates that have no entries for them (i.e. would not exist on the index of the wide-format df equivalent). This PR adds a better error message to handle this situation
> Bugfix: added exception handling to `expanding_stat` for missing dates

- macrosynergy/management/simulate/simulate_quantamental_data.py
- tests/simulate.py
Modify the `temporary_seed` function to gracefully handle cases where the seed is None or not an integer, ensuring no action is taken in such scenarios.
> Feature: Update `temporary_seed` functionality to handle None and non-integer seeds

- macrosynergy/visuals/score_visualisers.py
Introduce a new parameter to control the rotation of y-axis labels in the ScoreVisualisers.view_snapshot method, enhancing the visualization flexibility.
> Feature: Add `yticks_rotation` parameter to `ScoreVisualisers.view_snapshot`

- macrosynergy/compat.py
- macrosynergy/panel/adjust_weights.py
Introduce a compatibility check for the availability of `pd.DataFrame.applymap` and refactor the `adjust_weights_backend` function to utilize this check for improved compatibility with different pandas versions.
> Bugfix: Change compatibility check for pd.DataFrame.applymap

- macrosynergy/management/utils/sparse.py
- tests/unit/management/test_sparse.py
Add the option to score information state changes by either `diff` (default) or `level`.
In a previous PR (https://github.com/macrosynergy/macrosynergy/pull/2235), we modified for the normalisation, but not how we filtered to new information. Hence new information was captured as: `abs(Y(t) - Y(t-1)) > 0`
Which proxies the levels, but isn't exactly capturing it. Now with the levels, we assume that all the non-change is represented by zero (hence the filter: `diff_mask = values_df.abs() > 1e-12`).
> Feature: `InformationStateChanges` option to score by level

- macrosynergy/pnl/naive_pnl.py
- tests/unit/pnl/test_naive_pnl.py
Update the evaluate_pnls method to make the pnl_cats parameter optional and enhance validation logic with type checks. Added tests to ensure functionality with and without pnl_cats input.
> Feature: Make `pnl_cats` parameter optional in `NaivePnL.evaluate_pnls()`

- macrosynergy/pnl/naive_pnl.py
Adjust the benchmark date handling in the NaivePNL to ensure accurate filtering based on the specified date range.
> Bugfix: Fix NaivePNL benchmark start & end dates

- macrosynergy/management/utils/df_utils.py
- macrosynergy/panel/category_relations.py
- macrosynergy/signal/signal_return_relations.py
- tests/unit/management/test_utils.py
- tests/unit/panel/test_category_relations.py
- tests/unit/signal/test_signal_return_relations.py
Clarify the definition of "slip" in the code and adjust its application in the `CategoryRelations` and `SignalReturnRelations` classes
> Bugfix: Change the definition of "slip" in `apply_slip`

- macrosynergy/management/utils/sparse.py
- tests/unit/management/test_sparse.py
Introduce warnings when the 'eop_lag' column is missing in the `create_delta_data` function and its test. Update the `InformationStateChanges` documentation to specify the requirement of the 'eop_lag' column for accurate calculations. Also added an argument called `thresh` for winsorization on the output stage, implemented in the `sparse_to_dense` function
> Feature: `InformationStateChanges` - update documentation, add warnings for missing 'eop_lag' column, and add winsorise (`thresh`) functionality

- macrosynergy/management/utils/sparse.py
- tests/unit/management/test_sparse.py
Rename the 'winsorise' parameter to 'thresh' in the InformationStateChanges and sparse_to_dense methods, along with corresponding updates in the TestInformationStateChanges class. This naming mismatch originated in https://github.com/macrosynergy/macrosynergy/pull/2318
> Bugfix: Rename 'winsorise' parameter to 'thresh' in `InformationStateChanges.to_qdf()`

- macrosynergy/visuals/correlation.py
For groupby operations on dataframes with categorical data, the default of observed=False is deprecated and will be changed to True in a future version of pandas.
> Bugfix: `msv.correlation`, add observed parameter to down-sampling in correlation transformation

- macrosynergy/download/dataquery.py
- macrosynergy/download/fusion_interface.py
- macrosynergy/download/jpm_oauth.py
- tests/unit/download/test_dataquery.py
- tests/unit/download/test_fusion_interface.py
- tests/unit/download/test_jpmaqs.py
Implement the `JPMorganOAuth` class to provide common OAuth workflows for DataQuery API, DataQuery File API (see #2452), and Fusion API.
> Feature: Implement `JPMorganOAuth` to provide common OAuth workflows
