- README.md
- setup.py
> Pypi documentation

- tests/unit/management/test_shape_dfs.py
Fix floating point precission for the tests.
> Fix floating points

- pytest.ini
Minor changes to the pytesting configuration file.
> tests, pytest.ini

- setup.py
Re-configure the setup file to read the README file for PyPI.
> feature, setup - readme for PyPI

- .github/workflows/codeql-analysis.yml
- .github/workflows/python-package.yml
- .github/workflows/pythons-docs.yml
- macrosynergy/management/check_availability.py
- macrosynergy/panel/__init__.py
- macrosynergy/panel/category_relations.py
- macrosynergy/panel/historic_vol.py
- macrosynergy/panel/historic_volality.py
- macrosynergy/panel/make_relative_value.py
- macrosynergy/panel/view_timelines.py
- pytest.ini
- setup.py
- tests/simulate.py
- tests/unit/management/test_check_availability.py
- tests/unit/management/test_shape_dfs.py
- tests/unit/management/test_simulate_quantamental_data.py
Main changes:
* Panel, category relations functionality
* Rolling historical volatility estimates
* Continuous deployment pipeline
* PyPI README notes
> Release v0.0.3

- README.md
Automated PyPI stats added to README file.
> Adding additional information to README file

- setup.cfg
- setup.py
Setting up the branch to be for next (not yet) released of v.0.0.4 and added meta data in setup.cfg
> v0.0.4, next release

- macrosynergy/panel/category_relations.py
[1] check for chart variants 
[2] add same box to joint_plot method
[3] box_fill option: if set to True gives white background
Changes made. The position of the correlation table on joint_plot is more central as it conflicts with the distribution of data the least.
> Updated category_relations.

- macrosynergy/panel/historic_vol.py
Potentially requires more description but in the current form it should describe each subroutine sufficiently. Will add further if required.
> Document Strings added - potentially scope for greater description.

- macrosynergy/panel/Zero_Handler.py
- macrosynergy/panel/Zn_Scores.py
- macrosynergy/panel/historic_vol.py
Need to complete but adding the foundation level code. Finishing off in the next couple of hours.
> Work in Progress.

- macrosynergy/panel/make_zn_scores.py
Pandas problem - not logical problem.
> Pandas issue - believe fixed.

- macrosynergy/management/dq.py
Minor changes following discussion.
> Error message changed, and accounts for an empty DataFrame.

- macrosynergy/management/dq.py
Added functionality for downloading from DataQuery.
> Feature DataQuery download

- macrosynergy/management/dq.py
Changes made following earlier conversation.
Will email the working Jupyter Notebook.
> Changes made following earlier dicussion.

- docs/requirements.txt
requirements.txt file modified.
> sphinx_book_theme added.

- docs/source/man/context.rst
Updating the context.rst file to the main branch.
> Building out the context.rst file.

- docs/source/man/context.rst
> More modifications.

- macrosynergy/panel/category_relations.py
Relavant method:
def intersection_cids(self, df):
Isolates the shared cross_sections across the number of categories defined in the dataframe.
> Cross-section filter submitted.

- setup.py
> Version modified.

- macrosynergy/management/dq.py
Will aim to build out a more sophisticated solution now.
Used to understand how the simplest solution would perform.
> DQ Temporary solution.

- macrosynergy/management/dq.py
The majority of logic is finished.
Requires a few modifications and removal of print statements.
> Majority of the logic is complete.

- macrosynergy/management/dq.py
Believe the code is complete. Testing the algorithm at the moment.
> Batch tracking mechanism modified.

- setup.py
> Modification of setup.py

- macrosynergy/signal/target_positions.py
> Minor change to digital logic.

- setup.py
> ISRELEASED to True for PyPi.

- setup.py
> Incorrect version.

- macrosynergy/management/dq.py
Modifications made if a single metric is missing but the residual metrics are available.
> Accounts for inconsistent data across metrics.

- macrosynergy/management/dq.py
Validates that each metric column will be a floating point value.
One of the issues highlighted in the email.
> Minor changes: datatypes for each column.

- macrosynergy/management/dq.py
Minor changes but results in more stable, consistent performance.
> Minor changes to the delay logic - aligned to the size of the requests.

- macrosynergy/management/dq.py
Converging to a more stable design.
> Time delay increase.

- macrosynergy/management/dq.py
Believe the testing has now converged to a more stable design.
> Further testing & adjustments.

- setup.py
Modified setup.py ready for the next upload to PyPi.
> ISRELEASE set to False.

- setup.py
> New release.

- macrosynergy/panel/panel_calculator.py
- tests/unit/panel/test_panel_calculator.py
> Panel Calculation.

- macrosynergy/management/shape_dfs.py
- macrosynergy/panel/make_zn_scores.py
- tests/unit/management/test_shape_dfs.py
- tests/unit/management/test_simulate_quantamental_data.py
- tests/unit/panel/test_relative_value.py
- tests/unit/panel/test_zn_scores.py
Reopening old Pull Request and previous task.
> Continuation of redesign.

- macrosynergy/panel/category_relations.py
- tests/unit/panel/test_category_relations.py
- tests/unit/panel/test_zn_scores.py
Believe functionality is complete. 
Requires Unit Test to be developed.
> Outliers removed.

- macrosynergy/management/dq.py
Error catching. Workflow remains the same.
> ErrorHandling. Server Errors.

- macrosynergy/panel/panel_calculator_alt.py
- macrosynergy/panel/panel_calculator_alt2.py
- tests/unit/panel/test_panel_calculator.py
- tests/unit/panel/test_zn_scores.py
Commencing code review and concurrent testing.
> PanelCalculation

- macrosynergy/management/dq.py
df.real_date = pd.to_datetime(df.real_date)
> Date conversion.

- macrosynergy/management/dq.py
- macrosynergy/management/simulate_quantamental_data.py
- macrosynergy/panel/basket_performance.py
- setup.py
Reversion - changes required to adjust for four servers.
> DQ Bugfix.

- macrosynergy/management/dq.py
> NO_REFERENCE_DATA parameter.

- setup.py
> Version 11.

- macrosynergy/panel/basket.py
- macrosynergy/panel/basket_performance_class.py
- macrosynergy/signal/target_positions.py
- tests/simulate.py
- tests/unit/panel/test_basket_performance.py
- tests/unit/panel/test_relative_value.py
shape_dfs
=> last code break
category_relations
=> xcat_trims
basket
=> unit testst
delete old baskets
target_positions
missing asserts
> various jobs

- macrosynergy/panel/__init__.py
- macrosynergy/panel/basket.py
- tests/simulate.py
- tests/unit/panel/test_basket_performance.py
- tests/unit/panel/test_relative_value.py
basket.py -> develop.
Separate branch.
> Latest versions.

- macrosynergy/panel/correl_matrix.py
Correlation Matrix - code lift.
> Correlation Matrix.

- macrosynergy/panel/category_relations.py
Graphical changes. Multiple coefficient boxes.
> Category_Relations

- LICENSE
- MANIFEST.in
- README.md
Quickly modifying our docs and README file.
> Modify README and docs

- macrosynergy/dataquery/__init__.py
- setup.py
Fix package structure for macrosynergy.dataquery.
> Fix package structure and set to version 0.0.13

- README.md
Add examples for use cases of the DataQuery interface to the README file.
> Example of usage case added to README

- .github/workflows/integration-tests.yml
- macrosynergy/dataquery/api.py
Adding IP address, base url and
> Adding error message for DQ ask

- macrosynergy/dataquery/auth.py
Adding additional information for DQ response HTTP code not OK.
> DQ HTTP response code non-ok

- macrosynergy/pnl/naive_pnl.py
Fix mismatch of DataFrame dimensions.
> MSY-500 Naive PnL mis-match of shapes

- .github/workflows/pythons-docs.yml
- README.md
- docs/requirements.txt
- docs/source/conf.py
- docs/source/man/context.rst
- docs/source/man/howto.rst
- docs/source/ref/macrosynergy.dataquery.rst
- docs/source/ref/macrosynergy.management.rst
- docs/source/ref/macrosynergy.panel.rst
- docs/source/ref/macrosynergy.pnl.rst
- docs/source/ref/macrosynergy.signal.rst
- docs/source/ref/modules.rst
> Requirements

- README.md
- setup.py
Updating readme for extra explanations, also updating config file to …include development status.
> updating readme

- .github/workflows/python-test-pypi-package.yml
- .github/workflows/pythons-docs.yml
- README.md
- macrosynergy/__init__.py
- macrosynergy/dataquery/auth.py
- macrosynergy/management/check_availability.py
- macrosynergy/management/shape_dfs.py
- macrosynergy/panel/basket.py
- macrosynergy/panel/view_timelines.py
- macrosynergy/pnl/naive_pnl.py
- setup.py
- tests/integration/dataquery/test_dataquery.py
- tests/integration/test_testpypi_version.py
* Minor bug in view_ranges.
* Unkwown GitHub error.
* Handle GitHub.
* GitHub Python versions.
* PyPi 0.0.18
* Created workflow YAML for pushing to testPyPI
* naive_pnl some changes for efficiency
* Added worfklow for publishing to TestPyPI
* updated ms/__init__.py to get version from setup.py
* renamed file
* Create test_testpypi_version.py
* added comment
* #506 bugfix
changing Markdown image reference for Logo as per @Magnus167
* Updating rst files
* MSY-500 Naive PnL mis-match of shapes
* Update README.md
* Minor spelling mistake + adding documentation link
* Updating documentation website
* Updating documentation website
* Updating documentation website
* fixed bug arrising due to type errors
* Updating test repo (#521)
* Minor bug in view_ranges.
* Unkwown GitHub error.
* Handle …
> Feature/fix (#550)

- setup.py
Leaving `ISREALEASED=True` for now
> Updated setup.py for v0.0.20

- .github/workflows/python-test-pypi-package.yml
The Publish to TestPyPI workflow now runs integration tests
> added integration test to Publish to TestPyPI worklflow

- macrosynergy/pnl/naive_pnl.py
> Bugfix : naive_pnl.plot_pnls() - facet plots

- macrosynergy/panel/view_timelines.py
Closes https://github.com/macrosynergy/macrosynergy/issues/636
> Added xcat_grid to enable facetgraph for xcats

- .github/workflows/codeql-analysis.yml
Updated action for node16. 
(closes https://github.com/macrosynergy/macrosynergy/issues/645)
> updated code_ql action

- macrosynergy/panel/category_relations.py
Closes https://github.com/macrosynergy/macrosynergy/issues/664.
> Bugfix : Category relations with "cids" as separator 

- macrosynergy/panel/view_timelines.py
- tests/unit/panel/test_view_timelines.py
Fixed size issue with view_timelines.
Closes : https://github.com/macrosynergy/macrosynergy/issues/179
> Bugfix : view_timelines, size arg

- macrosynergy/panel/view_timelines.py
- tests/unit/panel/test_view_timelines.py
Closes : https://github.com/macrosynergy/macrosynergy/issues/659
> Feature : Single Chart Argument on View Timelines

- requirements.txt
- tests/unit/panel/test_view_timelines.py
Unittests now use mpl.("Agg") - the non-GUI backend
> Bugfix : Changed backend used for matplotlib in unittests

- macrosynergy/panel/panel_calculator.py
- tests/unit/panel/test_panel_calculator.py
The raise warning behaviour is now included in the unittest
> Bugfix : Added code for dropping empty series from panel_calculator() output

- macrosynergy/management/utils.py
- tests/unit/management/test_utils.py
#740 and #738 use this functionality.
The function has a place in utils, as the warning message needs to be consistent.
This also allows for easier testing. 
Unittest for drop_nan_series is included
> Feature : Implemented `utils.drop_nan_series`

- macrosynergy/panel/basket.py
> Feature : `size` argument for Basket.weight_visualiser()

- macrosynergy/panel/make_relative_value.py
- tests/unit/panel/test_relative_value.py
> Feature : make_relative_value basket 

- macrosynergy/panel/category_relations.py
Reverts macrosynergy/macrosynergy#761
> Revert "Feature : Adding a temporal heatmap to `CategoryRelations.reg_scatter()`"

- macrosynergy/pnl/naive_pnl.py
- tests/unit/pnl/test_naive_pnl.py
> Bugfix : `naive_pnl.make_long_pnl()` to accept `vol_scale=None`

- macrosynergy/management/check_availability.py
- macrosynergy/panel/view_timelines.py
Closes https://github.com/macrosynergy/macrosynergy/issues/721
> Bugfix : `check_availability()` plot sizes not independent

- macrosynergy/panel/view_timelines.py
Test using :
`pip install git+https://github.com/macrosynergy/macrosynergy@bugfix/vt_single_cid`.
Closes #820
> Bugfix : View Timelines, single CID charts legend

- macrosynergy/panel/linear_composite.py
- tests/unit/panel/test_linear_composite.py
> Bugfix: Linear Composites, missing `xcats` when using `xcat_agg`

- macrosynergy/pnl/naive_pnl.py
> Bugfix: Naive PNL - weekly rebal freq, attribute error 

- docs/static/05_dev_guide.md
Adding documentation around CI/CD, Pull requests, branch rules
> Docs: Added CI/CD documentation

- .github/workflows/python-publish-docs.yml
- .github/workflows/python-test-docs.yml
- docs/scripts/build_md.py
Adding flake8 to docs publish & test workflows.
Adding a failure warning when a file cannot be parsed.
> Bugfix: Adding tests and warnings to docs

- docs/static/01_context.md
- docs/static/index.md
- setup.py
> Chore: Merging hotfix (PR #981) to `develop`

- docs/assets/jpb-config.yml
The URL is currently pointing to a feature branch, changing to `main`
> Bugfix: Updating the URL for the logo in `docs/assets/jpb-config.yml`

- macrosynergy/management/utils.py
- macrosynergy/pnl/contract_signals.py
- macrosynergy/pnl/notional_positions.py
Suggesting splitting out the back-end calculations to be in actual matrix and vector formats (pd.DataFrame pivoted to wide and pd.Series). This should enable easier reading of what the functions actual does in terms of calculations.
> Feature/pnl ls - suggested refactoring

- .github/workflows/github-update-cache.yml
Action was missing the checkout step
> Bugfix: CI/CD, common cache

- macrosynergy/learning/panel_timeseries_split.py
> longbias fix

- docs/static/05_dev_guide.md
Updating Pull Requests>Merge Queueing section of the contribution guide
> Docs: Updating contribution guide

- docs/static/06_definitions.md
```bash
python -m pip install docs/requirements.txt
docs/scripts/build.bat
> Docs: Common definitions

- macrosynergy/visuals/correlation.py
- macrosynergy/visuals/plotter.py
This pull request adds a context manager to the correlation matrix plotting function, which ensures that the plot is properly closed after use. Additionally, it refactors the imports in the plotter.py file for better readability and maintainability.
> Bugfix: Add context manager to correlation matrix plotting

- macrosynergy/visuals/timelines.py
> Bugfix: Cross-Sectional mean is only interpreted across cids specified instead of globally across dataframe

- macrosynergy/panel/make_zn_scores.py
- tests/unit/panel/test_zn_scores.py
Significantly speeds up the expanding mean calculation.
> Feature: vectorize expanding mean in `make_zn_scores`

- docs/source/static_rsts/macrosynergy.download.rst
- docs/source/static_rsts/macrosynergy.learning.rst
- docs/source/static_rsts/macrosynergy.management.rst
- docs/source/static_rsts/macrosynergy.panel.rst
- docs/source/static_rsts/macrosynergy.pnl.rst
- docs/source/static_rsts/macrosynergy.signal.rst
- docs/source/static_rsts/macrosynergy.visuals.rst
This pull request adds references to the README.md files of the subpackages in the repository. This will provide better documentation and improve the overall organization of the repository.
> Feature: Add references to subpackage README.md files

- docs/gen.py
- docs/source/static_rsts/macrosynergy.download.rst
- docs/source/static_rsts/macrosynergy.learning.rst
- docs/source/static_rsts/macrosynergy.management.rst
- docs/source/static_rsts/macrosynergy.panel.rst
- docs/source/static_rsts/macrosynergy.pnl.rst
- docs/source/static_rsts/macrosynergy.signal.rst
- docs/source/static_rsts/macrosynergy.visuals.rst
Reverts macrosynergy/macrosynergy#1397
> Bugfix: Revert "Docs: Update subpackage READMEs and generate documentation"

- .github/workflows/python-publish-docs.yml
- .github/workflows/python-pypi-upload.yml
> Bugfix: Fix artifact upload having the incorrect versioning with deployment to github pages

- macrosynergy/visuals/facetplot.py
Reverts macrosynergy/macrosynergy#1422
> Bugfix: Revert "Feature: Speed up view_timelines"

- macrosynergy/visuals/facetplot.py
- macrosynergy/visuals/timelines.py
> Feature:  View Timelines

- macrosynergy/visuals/correlation.py
> Bugfix: Add check for empty dataframes in `msp.correl_matrix()`

- macrosynergy/management/utils/df_utils.py
- tests/unit/management/test_update_df.py
Refactoring to remove extra code and avoid pandas `SettingWithCopyWarning`
> Feature: Refactoring `update_df()` & `update_tickers()`

- macrosynergy/management/utils/df_utils.py
- tests/unit/management/test_utils.py
NOTE: The actual direction and application of slippage remains the same.
> Feature: Adding unittests for `msm.utils.apply_slip()`

- macrosynergy/management/utils/sparse.py
Add string and representation to the class.
> InformationStateChanges class str and repr representation

- macrosynergy/pnl/naive_pnl.py
- tests/unit/pnl/test_naive_pnl.py
> Feature: Adding a `leverage` parameter to `NaivePnL.make_pnl()` 

- macrosynergy/management/utils/df_utils.py
- tests/unit/management/test_utils.py
Closes https://github.com/macrosynergy/macrosynergy/issues/1859
> Refactor: Change sort-order for `update_df()` output

- macrosynergy/management/utils/sparse.py
- tests/unit/management/test_sparse.py
This pull request adds a new method to load information state changes from DF and integrates it into the ISC object. This allows for loading information state changes directly from DFs/CSVs
> Feature: Added method `InformationStateChanges.from_isc_df()`

- macrosynergy/panel/granger_causality_test.py
- macrosynergy/panel/historic_vol.py
- macrosynergy/panel/linear_composite.py
- macrosynergy/panel/make_blacklist.py
- macrosynergy/panel/make_relative_category.py
- macrosynergy/panel/make_relative_value.py
- macrosynergy/panel/make_zn_scores.py
- macrosynergy/panel/panel_calculator.py
Edits to docs for `make_relative_value` and `make_relative_category`. 
Other files have functions reordered for clarity but their docs will need to be reviewed separately.
> Docstring edits

- .gitignore
- docs/requirements.txt
- docs/source/conf.py
- macrosynergy/management/constants.py
- tests/utils.py
Splitting out the ProxyPnL PR into smaller changes for ease of reviewing.
> Feature: Proxy PNL minor changes

- macrosynergy/management/simulate/__init__.py
- macrosynergy/management/simulate/simulate_quantamental_data.py
Adding functionality for simulating Quantamental returns and signals.
> Feature: Function for simulating returns and signals

- macrosynergy/management/utils/__init__.py
- macrosynergy/management/utils/df_utils.py
- tests/unit/management/test_utils.py
- tests/utils.py
Functionality of estimating release frequency - split out into separate PR.
> Feature: Functionality of estimating frequency for a Quantamental time-series

- macrosynergy/download/dataquery.py
Enhance response validation logging by including the DataQuery Interaction ID for better traceability.
> Feature: Include DataQuery Interaction ID in response validation

- macrosynergy/download/dataquery.py
The current response validation mechanism forms an error message that includes the complete response text. This message formation is now conditional, thus preventing an additional overhead.
merge-after-#2256
> Bugfix: Refactor error handling in response validation

- macrosynergy/management/simulate/simulate_quantamental_data.py
- tests/simulate.py
- tests/unit/management/test_shape_dfs.py
- tests/unit/management/test_simulate_quantamental_data.py
Introduce a random seed for consistent output in the `make_qdf` function
> Feature: Add a seed argument to `make_qdf`

- macrosynergy/pnl/naive_pnl.py
Provide detailed metrics in the docstring for the PnL statistics table, improving clarity on the returned data.
> Docs: Enhance docstring for `NaivePnL.evaluate_pnls` statistics table

- macrosynergy/panel/__init__.py
- macrosynergy/panel/adjust_weights.py
- tests/unit/panel/test_adjust_weights.py
Introduce a new feature that modifies standard weights based on signal zn-scores.
> Feature: Implement `adjust_weights` functionality

- macrosynergy/compat.py
- macrosynergy/panel/adjust_weights.py
Update the variable name for better clarity and adjust its usage in the `adjust_weights.py` file accordingly.
> Bugfix: Rename `PD_APPLY_MAP` to `PD_NEW_MAP` for clarity

- macrosynergy/pnl/naive_pnl.py
- tests/unit/pnl/test_naive_pnl.py
Introduce a compounding parameter to control daily compounding of PnLs and update the y-axis label to reflect this change.
> Feature: `NaivePnL.plot_pnls()` to include `compounding`

- macrosynergy/learning/sequential/base_panel_learner.py
- macrosynergy/learning/sequential/signal_optimizer.py
- tests/unit/learning/sequential/test_signal_optimizer.py
This PR is sizable because it needed a little restructure to allow for hyperparameter tuning to be optional
> Feature: Allow optional hyperparameter tuning

- macrosynergy/pnl/historic_portfolio_volatility.py
- tests/integration/pnl/test_historic_portfolio_volatility.py
- tests/unit/pnl/test_historic_portfolio_vol.py
Introduce a minimum observation parameter to covariance estimation functions to ensure sufficient data for accurate calculations
> Bugfix: Add minimum observation parameter to covariance estimation functionality

- macrosynergy/download/fusion_interface.py
- tests/unit/download/test_fusion_interface.py
Enhance API call handling by implementing better rate limiting and error logging
> Bugfix: Refactor Fusion API delay handling

- macrosynergy/download/fusion_interface.py
- tests/unit/download/test_fusion_interface.py
Introduce a new method to fetch all series members for all datasets in the JPMaQS product and add corresponding tests to ensure functionality.
> Feature: Implement `JPMaQSFusionClient.get_all_seriesmembers_for_all_datasets()`
